### ISSUE TITLE
難所を攻略する際には黒線追跡しない？

### ISSUE THREAD

**Issue by MaxMEllon** [SLP-ETR-public/ETR2015_model#3]
この[図](https://github.com/SLP-ETR-public/ETR2015_model/blob/ddc9c3fcd81608b643968344ae84cd5829ffeff2/diagram/usecase/01/usecase.png)をみると黒線追跡するのは，ベーシックステージのみに見える．
ボーナスステージで黒線追跡することはないのかどうか

**Comment by MaxMEllon** [comment]
( 走行する ) と  ( 難所を攻略する ) は粒度がちがう気がする．

( 走行する ) に 難所攻略は含まれるのではないか

**Comment by kattsun17** [comment]
includeしてみました!!

**Comment by MaxMEllon** [comment]
gitterにコメントしました！

**Comment by MaxMEllon** [comment]
[1a1120](https://github.com/SLP-ETR-public/ETR2015_model/tree/1a112086b73ab79b2976a0dbbf3522eda92f5f85)

修正済
